# Generated by Django 5.2.8 on 2025-11-29 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='Projects',
            new_name='project',
        ),
    ]
