# Generated by Django 5.2.8 on 2025-11-29 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_projects_task_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskdetails',
            name='assigned_to',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
