# Generated by Django 5.2.8 on 2025-11-19 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='Projects',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tasks.projects'),
        ),
    ]
