# Generated by Django 5.2.8 on 2025-12-17 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_taskdetails_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskdetails',
            name='assigned_to',
        ),
    ]
