# Generated by Django 5.2.8 on 2025-11-20 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_employees_task_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Projects',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks.projects'),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ManyToManyField(related_name='tasks', to='tasks.employees'),
        ),
    ]
