# Generated by Django 5.2.8 on 2025-11-24 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_task_projects_alter_task_assigned_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='Start_date',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='is_complated',
            new_name='is_completed',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='uodate_at',
            new_name='updated_at',
        ),
    ]
